### ISSUE TITLE
Gyros and accrs static biases are not used in ins_gnss

### ISSUE THREAD

**Issue by Alevs2R** [rodralez/NaveGo#34]
I checked the code of ins_gnss and there is no usage of ab_sta and gb_sta.
There is only one line with this variables:
```
b(1,:)  = [imu.gb_sta, imu.ab_sta];
```
But there is no practical benefit in it. It confused me at first. Maybe remove this input or add special comment in ins_gnss.m?

**Comment by rodralez** [comment]
Hi Alevs,

Thank you very much for exposing another bug.

Yes, static bias is not used in NaveGo and this is wrong. 

Static bias can be modeled as a sum of a deterministic part and a stochastic part. The deterministic static bias can be found using a calibration method in a laboratory. The stochastic static bias provides a constant variation in the bias every time the IMU is switched on (run-to-run variation). This error is compensated by the Kalman filter.

Previous versions of NaveGo compensated the stochastic static biases but we realized that this error was also captured by the stochastic dynamic biases, so the compensation of stochastic static biases was dropped and the state vector was reduced from 21 states to 15 states.

That's why we forgot about the static bias, but the deterministic part has to be still compensated. 

The following code has been added to the ins_gnss.m file (lines 249 and 250):
`   
wb_corrected = imu.wb(i,:)' + gb_dyn - imu.gb_sta';
fb_corrected = imu.fb(i,:)' + ab_dyn - imu.ab_sta';
`
Now the deterministic part of the static bias is compensated.

I have also changed the line 211:
`
b(1,:)  = [imu.gb_dyn, imu.ab_dyn];
`
Once again, thank you very much for your feedback. We will be happy if you become officially a NaveGo's contributor. Just let me know if you are interested at rodralez at frm utn edu ar.

Regards.
